### ISSUE TITLE
[Doc] Document how to diff two stats json files

### ISSUE THREAD

**Issue by vire** [smelukov/statoscope#57]
I saw the `diff` two stats feature already exists but I'm not sure how to use it properly.

**Comment by smelukov** [comment]
Hi! You can just drop multiple stats to https://statoscope.tech and press the `Diff` button
Or, if you're using the webpack plugin, then use [additionalStats](https://github.com/smelukov/statoscope/tree/master/packages/ui-webpack#optionsadditionalstats-string) property

**Comment by zubair-bashir** [comment]
@smelukov 

I'm trying to generate the JSON stats on every build and a single report file that is loaded with previous stats so that I can run a diff across the different builds' stats data. Here's the structure I'm aiming for. One report file which is loaded with other reports data on every new build:

<img width="350" alt="image" src="https://github.com/statoscope/statoscope/assets/89123863/372b0a37-3e51-4b07-ad02-701a44feccad">

Here's my config:

<img width="992" alt="image" src="https://github.com/statoscope/statoscope/assets/89123863/5bef11d9-abb1-4a68-898f-bb237f8cb877">

The JSON stats are generated correctly and so is the HTML report file which over-rides the earlier on every build with the same name. But when opening the report file I only get the first build's stats even though the other builds' content is correctly present inside the report HTML file.


Any idea what might be happening here.
